<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Months Since Most Recent Bankruptcy</name>
  <uuid>1b3122fe-7ec5-434b-859e-0598d86da79e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'an Applicant Bankruptcy Date List' to  a date  in 'Applicant Bankruptcy Date List', sorted in ascending order ;
    set 'variable1' to the number of years between the requestDate of Application and 'an Applicant Bankruptcy Date List' ; 
if
	'Bankruptcy Indicator' is true and  variable1 is defined 
then
	 set decision to variable1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
