<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>40fda316-2a9d-4420-a8ec-270c1ec3849e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add Not Eligible to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
