<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Repossession Indicator</name>
  <uuid>02597551-5de4-498a-90d3-d70925b070e9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ if 
	'Applicant Repossession Date List' are defined then 
	set decision to true ;
     
else 
	set decision to false ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
