<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Payment to Income Maximum Payment</name>
  <uuid>8a6fbb67-6581-424b-94a0-ccc768175b7c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to ('Maximum Payment to Income Ratio' * the tdsIncome of Application)/100 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
