<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Number of Qualifying Tradelines</name>
  <uuid>ecc97fd7-c62d-495e-b807-ed30418226d4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Qualifying Debt Date List' are defined 
then
	set decision to the number of elements in 'Qualifying Debt Date List' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
