<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Oldest Qualifying Tradeline Date</name>
  <uuid>daa6cb97-9e60-4636-aa80-a2989c09a634</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'variable1' to 'Qualifying Debt Date List' , sorted in descending order ; 
    then 
 for each date in variable1 : 
	- set decision to this date; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
