<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Auto Approve Output</name>
  <uuid>bf5eb02b-bc9d-4c14-b4c6-9b0ca141cd0b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the worksheetAmount of Application ≤ 'Amount to Finance Auto Approve Threshold'
    then
	set decision to a new Amount to Finance Recommended Outcome where
		the Message is "No Message" , 
		the Output is Auto Approve ;
        ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
