<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Manual Review Output</name>
  <uuid>4214c832-5eac-494c-824c-49ccc8634fec</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the worksheetAmount of Application ≤ 'Amount to Finance Manual Review Threshold' 
    and the worksheetAmount of Application > 'Amount to Finance Auto Approve Threshold' 
then
	set decision to a new Amount to Finance Recommended Outcome where
		the Message is "Amount to Finance Exceeds Auto Approve Amount" , 
		the Output is Manual Review ;
        ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
