<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Distinct Function</name>
  <uuid>534cf77b-3cd7-4766-9b11-3d21d60cab12</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to decision , made distinct; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
