<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Trade Equivalent Monthly Payment Amount</name>
  <uuid>0a0bed0a-207e-47ac-8f6b-e78afc7e3aaa</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'aCustomer' to a Customer in Customer ; 
    
	set 'variable1' to a number in 'Trade Payment Frequency' ; 
    
    if the tradePmtAmt of the TransUnion Report of the Credit Bureau Report of aCustomer  = 0 
     then 
	add 0 to decision ; 


else 
	add (variable1 * the tradePmtAmt of the TransUnion Report of the Credit Bureau Report of aCustomer )/12 to decision; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
