<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Number Of Qualifying New Tradelines In the Last 6 Months</name>
  <uuid>6bee3da9-546c-45a1-bc46-ab17d890f993</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each date in 'Qualifying Debt Date List', where each date is after or the same as 'Six Month Date Threshold' : 
	- add this date to decision;
	]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
