<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total Installment Monthly Debt Obligation</name>
  <uuid>1fef3b36-5680-4a4a-956d-fbd2340a9685</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each number in 'Installment Trade Monthly Debt Obligation' : 
	-  set decision to the sum of 'Installment Trade Monthly Debt Obligation'; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
