<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Application Credit Risk Tier</name>
  <uuid>fa9a6011-d732-4660-bf54-c2aaa3817eb6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
   set 'an Applicant Credit Risk' to a Tier in 'Applicant Credit Risk Tier';
   set 'a customer' to a Customer in Customer ; 
   
	set 'variable1' to 'an Applicant Credit Risk' 
	where the customerType of 'a customer' is "Primary" ; 
    then 
	set decision to variable1 ; 
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
