<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Application Credit Risk Tier</name>
  <uuid>7689d158-aacc-4ccd-8df8-8d154f0af9b4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
    set 'variable2' to a Tier  in 'Applicant Credit Risk Tier' ;
    then 
	for each Customer in Customer , 
	where the customerType of each Customer is "Primary" , : 
	- set decision to variable2;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
