<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Auto Decline Outcome</name>
  <uuid>1042ff2d-7ca0-4226-b9f1-15e705b26e4d</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'an Applicant Credit History Recommended Outcome' to an Auto Approve/Manual Review/Auto Decline in 'Applicant Credit History Recommended Outcome' ;
    if 'an Applicant Credit History Recommended Outcome' is one of { Auto Decline } then 
	set decision to Auto Decline ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
