<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Manual Review Outcome</name>
  <uuid>2fb4f0d3-3809-4d54-871a-33926408e9b7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'an Applicant Credit History Recommended Outcome' to an Auto Approve/Manual Review/Auto Decline in 'Applicant Credit History Recommended Outcome' ;
    if 'an Applicant Credit History Recommended Outcome' is one of { Manual Review } then 
	set decision to Manual Review ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
