<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Collection Indicator</name>
  <uuid>ad6bb0ee-7025-40bd-84e3-eff53e58725c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Applicant Collection Date List' are defined 
then
	set decision to true ;
    
else 
	set decision to false ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
