<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Auto Decline Output</name>
  <uuid>897ebdc3-c6a6-4395-9a36-a8459b462ba4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Conditional Approval Maximum Amount to Finance'> 'Amount to Finance Manual Review Threshold'
then
	set decision to Auto Decline ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
