<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total Revolving Monthly Debt Obligation</name>
  <uuid>c92d4a37-6241-4083-9a9d-f7d760a77622</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[for each number in 'Revolving Trade Monthly Debt Obligation' : 
	- set decision to the sum of 'Revolving Trade Monthly Debt Obligation';  ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
