<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Max Of Application Monthly Rent Amount</name>
  <uuid>5bee15f3-ce7d-440d-ab05-329e4c0bc5b0</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the maximum of 'Application Monthly Rent Amount' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
