<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>f70eb01b-69e4-43a1-b16a-14f74a01fda2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
