<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total Open Monthly Mortgage Payment Amount</name>
  <uuid>b80c65b7-d69e-4ccb-8005-0f937d4c6261</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 

	set 'aCustomer' to a Customer in Customer   ; 
    
	set 'aDebt' to a Debt in the Debts of aCustomer 
	where the portfolioType of this Debt is "Mortgage" and the balAmt of this Debt > 0 ; 
        
if 
aDebt is defined then 
set decision to the monthlyPmtAmt of aDebt ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
