<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Months Since Most Recent Repossession</name>
  <uuid>36947d6f-cb47-4186-8d3a-cb227bf0a4b2</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'an Applicant Repossession Date List' to  a date  in 'Applicant Repossession Date List' , sorted in ascending order ;
    set 'variable1' to the number of years between the requestDate of Application and 'an Applicant Repossession Date List' ; 
if
	'Repossession Indicator' is true and  variable1 is defined 
then
	 set decision to variable1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
