<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total Credit Bureau Monthly Debt Obligation</name>
  <uuid>e31f1aff-4f2b-416d-9286-16a3e523fe6f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to ('Total Revolving Monthly Debt Obligation'+ 'Total Installment Monthly Debt Obligation' );]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
