<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>ddcc7538-17a2-4e63-aa5f-c4b2ae0f58b7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add null to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
