<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>290f8195-c7b9-4825-ae18-b4fe8f0187b7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
