<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>66a72353-4096-43d3-b563-3ae65db7ac8b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
