<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total Debt Service Ratio II</name>
  <uuid>0973e67b-b95f-4929-b2e2-5f620866f425</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	the tdsIncome of Application > 0 
	and the worksheetTotalMthPay of Application = 0 
then
	set decision to ((the maximum payment computed from 
	Customer being Customer , 
	Application being Application + the total monthly debt payment obligation service computed from 
	Customer being Customer , 
	Application being Application ) / the tdsIncome of Application) * 100 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
