<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Applicant Age</name>
  <uuid>48892087-ab73-4a7a-aa81-fc814346462f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'variable1' to a date in the dateOfBirths of Customer ; 
     then 
	add the number of years between the requestDate of Application and variable1 to decision ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
