<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Tier D PTI LTV Recommended Outcome</name>
  <uuid>711e62b7-4a04-488d-ae1e-05c0e0f1d45b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions
set 'a credit risk tier' to the application credit risk tier service computed from
		Customer being Customer ;
if
	'a credit risk tier' is Tier D 
then
	set decision to 'Tier D PTI LTV Recommended Outcome' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
