<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Tier A PTI LTV Recommended Outcome</name>
  <uuid>d56ddae0-3ce6-4bd2-86cd-90a8c993e1a1</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Application Credit Risk Tier' is Tier A 
then
	set decision to 'Tier A PTI LTV Recommended Outcome' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
