<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Tier C PTI LTV Recommended Outcome</name>
  <uuid>a29c0c1b-75cf-45b7-b950-eca53b1ae422</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	'Application Credit Risk Tier' is Tier C 
then
	set decision to 'Tier C PTI LTV Recommended Outcome' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
