<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Asset Age</name>
  <uuid>e69477e5-56fd-4fc0-a755-bb1ee9fc29b5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ definitions 
	set 'variable1' to a year from the year of the requestDate of Application ; 
     then 
	set decision to `{ the year of Asset -  variable1 }`;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
