<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Months Since Most Recent Collection</name>
  <uuid>7c4c7b37-0f72-455d-ba01-6ac5398ba9df</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[definitions 
	set 'an Applicant Collection Date List' to  a date  in  'Applicant Collection Date List' , sorted in ascending order ;
    set 'variable1' to the number of years between the requestDate of Application and 'an Applicant Collection Date List' ; 
if
	'Collection Indicator' is true and  variable1 is defined 
then
	 set decision to variable1;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
