<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Consumer Proposal Indicator</name>
  <uuid>30578ea8-5b6a-43fc-aa6c-69e71a9a17f7</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[ if 
	'Applicant Consumer Proposal Date List' are defined then 
	set decision to true ;
     
else 
	set decision to false ; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
