<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Conditional Approval Maximum Payment</name>
  <uuid>9b352bc7-d866-4e50-b9da-ac5b79de4075</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the minimum of { 'Total Debt Service Maximum Payment', 'Payment to Income Maximum Payment' } ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
