<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>0c78cadf-bb5b-469c-81af-bc7f7702b707</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
